name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        sudo apt-get install aria2
        sudo mkdir /etc/aria2 
        sudo touch /etc/aria2/aria2.session 
        sudo chmod 777 /etc/aria2/aria2.session
  
    - name: Downloading Ngrok.
      run: |
          sudo wget  https://raw.githubusercontent.com/gdgrtmnv1222/gdgrtmnv1222.github.io/main/aria2.conf
          sudo mv /home/runner/work/gdgrtmnv1222.github.io/gdgrtmnv1222.github.io/aria2.conf /etc/aria2
          
    - name: Downloading Ngrok2.
      run: |
         wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -O Ngrok.zip
         unzip "Ngrok.zip"
         
    - name: Download2ing Ngro43k2.
      run: |
        curl https://rclone.org/install.sh | sudo bash
        cd  /home/runner/
        sudo mkdir .config
        ls
        
     


      
       
    
         
    - name: Download2ing Ngro3k2.
      run: |
         ./ngrok authtoken 1dDm2DomElU8uomhMviz2z93qVo_7Q8fk6EzBCper6TMkT1mq
         sudo aria2c --conf-path=/etc/aria2/aria2.conf & ./ngrok http 6800
