name: Jekyll site CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: |
        sudo apt-get install aria2
        sudo mkdir /etc/aria2 
        sudo touch /etc/aria2/aria2.session 
        sudo chmod 777 /etc/aria2/aria2.session
  
    - name: Downloading Ngrok.
      run: |
        cd /etc/aria2
         sudo wget https://raw.githubusercontent.com/gdgrtmnv1222/gdgrtmnv1222.github.io/main/aria2.conf
         - name: staert.
      run: |
        sudo aria2c --conf-path=/etc/aria2/aria2.conf
      
